version: "3"
services:
  web:
    image: marknipes/get-started:part2
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
